server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /config.js {
        default_type application/javascript;
        add_header Cache-Control "no-store";
        return 200 "window.MARTIN_URL = '${MARTIN_URL}';";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
