ALTER TABLE orchard_share_tokens
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ADD COLUMN can_harvest BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN can_water BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN can_add_photos BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE orchard_share_tokens
SET
    can_harvest = permission = 'harvest_watering',
    can_water = permission IN ('watering', 'harvest_watering');

DROP INDEX orchard_share_tokens_orchard_permission_idx;

ALTER TABLE orchard_share_tokens
    DROP CONSTRAINT orchard_share_tokens_permission_check,
    DROP COLUMN permission,
    ADD CONSTRAINT orchard_share_tokens_id_key UNIQUE (id);

CREATE INDEX orchard_share_tokens_orchard_idx
    ON orchard_share_tokens (orchard_id);
